### ISSUE TITLE
Support for .NET Framework

### ISSUE THREAD

**Issue by ryab777** [Research-Institute/json-api-dotnet-core#154]

**Comment by jaredcnance** [comment]
We currently target  netstandard1.6 and as such support any of the implementations (including v4.6.1) https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

If you are referring to ASP.Net MVC or WebAPI (any of the web frameworks prior to ASP.Net Core) that cannot be done because we require the core middleware and DI systems.

If you're unfamiliar with the differences between dotnet core and ASP.Net core, pleas take a look at this https://www.google.com/amp/s/andrewlock.net/understanding-net-core-netstandard-and-asp-net-core/amp/
