### ISSUE TITLE
NullReferenceException traversing HasMany Relationship

### ISSUE THREAD

**Issue by rkischuk** [Research-Institute/json-api-dotnet-core#155]
In a .NET Core 2 app using JsonApiDotNetCore 2.1.3, I have 2 models mapped against postgres. The default controllers are working correctly for both models (we would normally disable controller access to `AuthenticationToken`, but we enabled it for debugging).

User.cs:
```
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using JsonApiDotNetCore.Models;

public class User : Identifiable {

    [Key]
    [Column("id")]
    public override int Id { get; set; }

    [Attr("email")]
    [Column("email")]
    public string Email { get; set; }

    [HasMany("authentication_tokens")]
    public virtual ICollection<AuthenticationToken> AuthenticationTokens { get; set; }
}
```

AuthenticationToken.cs:
```
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using JsonApiDotNetCore.Models;

public class AuthenticationToken : Identifiable {

    [Key]
    [Column("id")]
    public override int Id { get; set; }

    [Attr("body")]
    [Column("body")]
    public string Body { get; set; }

    [Attr("user_id")]
    [Column("user_id")]
    public int UserId { get; set; }

    [HasOne("user")]
    public virtual User User { get; set; }
}
```
So then, in some test code, I attempt to execute:
```
        var user = await service.GetAsync(5325);
        int i = user.AuthenticationTokens.Count;
```
At which point, referencing the collection raises:
```
fail: JsonApiDotNetCore.Middleware.JsonApiExceptionFilter[0]
      An unhandled exception occurred during the request
System.NullReferenceException: Object reference not set to an instance of an object.
   at UsersController.<GetAsync>d__2.MoveNext() in /Users/rkischuk/code/DotNetHasMAny/UsersController.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()
```
Note that the route `http://localhost:5000/users/5235/relationships/authentication_tokens` returns a result as expected.

I would expect to be able to traverse the relationship to this list without issue.

**Comment by rkischuk** [comment]
Additionally interesting... I created this simple case to isolate and verify the issue.

In the original application I am working in, if I call `dbContext.authenticationTokens.ToList().Take(1)` before attempting to traverse the `HasMany` relationship, the relationship resolves correctly.

**Comment by jaredcnance** [comment]
@rkischuk when you call `GET /{model}/{id}/relationships/{relationshipName}` it gets routed to [`GetRelationshipsAsync`](https://github.com/Research-Institute/json-api-dotnet-core/blob/master/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs#L127) controller method. Here you can see what happens under the covers. In order to load the relationships it calls the [`IGetRelationshipsService`](https://github.com/Research-Institute/json-api-dotnet-core/blob/master/src/JsonApiDotNetCore/Services/Contract/IGetRelationshipsService.cs#L14) implementation which exists [here](https://github.com/Research-Institute/json-api-dotnet-core/blob/master/src/JsonApiDotNetCore/Services/EntityResourceService.cs#L81) (if you are using EF).

So, I wanna back up a bit and discuss what you are actually doing. When you call [`GetAsync`](https://github.com/Research-Institute/json-api-dotnet-core/blob/master/src/JsonApiDotNetCore/Services/EntityResourceService.cs#L61), the only relationships that will be side loaded are ones in the `include` query. So, in order to include the relationship in the query you need to call `dbContext.Users.Include(u => u.AuthenticationTokens)` (since EF does not support [lazy loading yet](https://github.com/aspnet/EntityFrameworkCore/issues/3797). 

If you can explain a little more about what you're trying to do I should be able to help. I expect what you're trying to do actually belongs in the service or repository layer rather than the controller.

**Comment by jaredcnance** [comment]
@rkischuk closing this, but feel free to re-open it if your question has not been answered.
